### PR TITLE
optimalization prime

### PR DESCRIPTION
**Pull request by MatejMagat305**
<!--

Please title your PR as follows: `time: fix foo bar`. 
Always start with the thing you are fixing, then describe the fix.
Don't use past tense (e.g. "fixed foo bar").

Explain what your PR does and why.

If you are adding a new function, please document it and add tests:

```
// foo does foo and bar
fn foo() {

// file_test.v
fn test_foo() {
    assert foo() == ...
    ...
}
```

If you are fixing a bug, please add a test that covers it.

Before submitting a PR, please:
  - run the tests with `./bin/test`

I try to process PRs as soon as possible. They should be handled within 24 hours.

Applying labels to PRs is not needed.

Thanks a lot for your contribution!

->

### CODE REVIEW

**Review by ulises-jeremias — APPROVED** [review]

**Comment by ylluminate** [comment]
@MatejMagat305 did you have a before/after benchmark to indicate if there were any performance differentials? I suppose I'm interpreting your "optimization" as such.

**Comment by MatejMagat305** [comment]
@ylluminate  Well it is generally know that at  prime number is the best way sqrt(n) and at fisrt 1000 it is aprox 1/6 number ..., what the problem ?

**Comment by JalonSolov** [comment]
If your optimization is for speed, he was wondering the difference in speed between the old code and your changes.  If the optimization is for accuracy, it would be nice to know that difference, as well.

**Comment by ulises-jeremias** [comment]
I did a quick comparison locally and was able to validate the optimization in performance. But for the future I'll start requesting that kind of information from the authors of the PRs 😊

**Comment by ylluminate** [comment]
That's cool @ulises-jeremias. It would be pretty nice if we had a benchmark component of the CI, but I suppose that's some time out yet.

**Comment by MatejMagat305** [comment]
@JalonSolov @ylluminate @ulises-jeremias again one sorry, next time I will

**Comment by ylluminate** [comment]
@MatejMagat305 no - it's fine, really. Don't feel bad, I just think it would be both interesting and helpful to be able to recognize such differentials. Like I said, an automated mechanism would be ideal, but Ulises adding such instructions or whatnot would also be helpful. Definitely do now want you to feel as though you did something "wrong."

**Comment by MatejMagat305** [comment]
@ylluminate no I agree with you, it should be verify be brenchmark, I m enjoy to oficial brenchmarks in Vlang

**Pull request merged**
