### PR TITLE
add unsafe variants

### PR DESCRIPTION
**Pull request by MatejMagat305**
at least now this is only draf and use case is https://github.com/MatejMagat305/Vsimulations

### CODE REVIEW

**Comment by ulises-jeremias** [comment]
@MatejMagat305 hey! I really appreciate your efforts improving VCL, but will be great if you can create issues or discussions after creating the PRs so I can guide you on the best path or the expected usage of the lib 😊 

I think we don't need to add extra methods. We just need to make this more flexible here https://github.com/vlang/vsl/blob/4dc518a6172a8c1127a713efbeec0b45902aea59/vcl/kernel.c.v#L146

**Comment by ulises-jeremias** [comment]
@MatejMagat305 I just did this [commit](https://github.com/vlang/vsl/commit/7079aaa9ac206f38c7b5ad54acf52cff0d7e8da1). It makes it possible to pass the underlying buffer as argument 😊 so It fixes your issue!

```v
vector_of_planets := . . .

<-kernel.run(vector_of_planets.buffer())
```

**Comment by ulises-jeremias** [comment]
> @MatejMagat305 I just did this [commit](https://github.com/vlang/vsl/commit/7079aaa9ac206f38c7b5ad54acf52cff0d7e8da1). It makes it possible to pass the underlying buffer as argument blush so It fixes your issue!
> 
> ```v
> vector_of_planets := . . .
> 
> <-kernel.run(vector_of_planets.buffer())
> ```

I'll close the PR as soon as you can confirm this unblocks you 😊

**Comment by MatejMagat305** [comment]
sorry, next time I open .....

**Pull request closed without merging**
